fix: android build

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,10 +1,11 @@
 name: Deployment
-on:
-  workflow_dispatch:
-  pull_request:
-    branches:
-      - dev
-    types: [closed]
+on: [push]
+# on:
+#   workflow_dispatch:
+#   pull_request:
+#     branches:
+#       - dev
+#     types: [closed]
 jobs:
   increment_version:
     runs-on: macos-latest
@@ -105,8 +106,8 @@ jobs:
           mkdir release
           fastlane package_apk
           cp "app/build/outputs/apk/release/app-release.apk" ${{env.APK_LOCATION}}
-          fastlane submit_to_google
-          fastlane s3_upload
+          # fastlane submit_to_google
+          # fastlane s3_upload
 
       - name: Send slack notification
         if: always()
@@ -126,75 +127,75 @@ jobs:
             { "title": "Pull Request", "value": "${env.GITHUB_SERVER_URL}/${env.GITHUB_REPOSITORY}/pull/${{ steps.pr.outputs.pull_request_number }}"}
             ]
 
-  internal_release_ios:
-    name: "iOS deploy"
-    needs: increment_version
-    runs-on: macos-latest
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v2
-        with:
-          token: "${{ secrets.GIT_ACCESS_TOKEN }}"
+  # internal_release_ios:
+  #   name: "iOS deploy"
+  #   needs: increment_version
+  #   runs-on: macos-latest
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v2
+  #       with:
+  #         token: "${{ secrets.GIT_ACCESS_TOKEN }}"
 
-      - name: Get Pull Request Number
-        id: pr
-        run: echo "::set-output name=pull_request_number::$(gh pr view --json number -q .number || echo "")"
-        env:
-          GITHUB_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
+  #     - name: Get Pull Request Number
+  #       id: pr
+  #       run: echo "::set-output name=pull_request_number::$(gh pr view --json number -q .number || echo "")"
+  #       env:
+  #         GITHUB_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
 
-      - name: Setup node
-        uses: actions/setup-node@v1
-        with:
-          node-version: '16.x'
+  #     - name: Setup node
+  #       uses: actions/setup-node@v1
+  #       with:
+  #         node-version: '16.x'
 
-      - name: Run fastlane setup
-        env:
-          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
-          CERTS_REPO_URL: ${{ secrets.CERTS_REPO_URL }}
-          MATCH_REPO_URL: ${{ secrets.CERTS_REPO_URL }}
-          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
-          FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
-          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD:  ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
-          FASTLANE_APP_IDENTIFIER: ${{ secrets.FASTLANE_APP_IDENTIFIER }}
-          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
-          FASTLANE_APPLE_ID: ${{ secrets.FASTLANE_APPLE_ID }}
-          FASTLANE_ITC_TEAM_ID: ${{ secrets.FASTLANE_ITC_TEAM_ID }}
-          FASTLANE_TEAM_ID: ${{ secrets.FASTLANE_TEAM_ID }}
-          ASC_KEY: ${{ secrets.ASC_KEY }}
-          ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
-          ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
-        run: |
-          git config --global url."https://".insteadOf git://
-          xcodebuild -version
-          yarn install
-          git clone "https://${{ secrets.ACCESS_TOKEN }}@github.com/docknetwork/react-native-sdk.git" ../wallet-sdk
-          yarn --cwd ../wallet-sdk install
-          yarn sync-sdk
-          yarn build-sdk
-          echo "BUILD_NUMBER=$(node print-build-number)" >> $GITHUB_ENV
-          git clone "${{ secrets.CERTS_REPO_URL }}" ./certs
-          # Pull env variables from certs repo
-          # It will inject sentry token in the JS thread
-          cp -rf ./certs/.env ./
-          cp -rf ./certs/GoogleService-Info.plist ./ios/
-          cd ./ios
-          pod install
-          fastlane build_upload_testflight
+  #     - name: Run fastlane setup
+  #       env:
+  #         ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
+  #         CERTS_REPO_URL: ${{ secrets.CERTS_REPO_URL }}
+  #         MATCH_REPO_URL: ${{ secrets.CERTS_REPO_URL }}
+  #         MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
+  #         FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
+  #         FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD:  ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
+  #         FASTLANE_APP_IDENTIFIER: ${{ secrets.FASTLANE_APP_IDENTIFIER }}
+  #         FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
+  #         FASTLANE_APPLE_ID: ${{ secrets.FASTLANE_APPLE_ID }}
+  #         FASTLANE_ITC_TEAM_ID: ${{ secrets.FASTLANE_ITC_TEAM_ID }}
+  #         FASTLANE_TEAM_ID: ${{ secrets.FASTLANE_TEAM_ID }}
+  #         ASC_KEY: ${{ secrets.ASC_KEY }}
+  #         ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
+  #         ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
+  #       run: |
+  #         git config --global url."https://".insteadOf git://
+  #         xcodebuild -version
+  #         yarn install
+  #         git clone "https://${{ secrets.ACCESS_TOKEN }}@github.com/docknetwork/react-native-sdk.git" ../wallet-sdk
+  #         yarn --cwd ../wallet-sdk install
+  #         yarn sync-sdk
+  #         yarn build-sdk
+  #         echo "BUILD_NUMBER=$(node print-build-number)" >> $GITHUB_ENV
+  #         git clone "${{ secrets.CERTS_REPO_URL }}" ./certs
+  #         # Pull env variables from certs repo
+  #         # It will inject sentry token in the JS thread
+  #         cp -rf ./certs/.env ./
+  #         cp -rf ./certs/GoogleService-Info.plist ./ios/
+  #         cd ./ios
+  #         pod install
+  #         fastlane build_upload_testflight
 
-      - name: Send slack notification
-        if: always()
-        uses: edge/simple-slack-notify@master
-        env:
-          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
-        with:
-          channel: '#wallet-bot'
-          status: ${{ job.status }}
-          success_text: 'iOS ${env.BUILD_NUMBER} completed successfully'
-          failure_text: 'iOS build failed'
-          cancelled_text: 'iOS build was cancelled'
-          fields: |
-            [{ "title": "Repository", "value": "${env.GITHUB_REPOSITORY}", "short": true },
-            { "title": "App version", "value": "${env.BUILD_NUMBER}", "short": true },
-            { "title": "Action URL", "value": "${env.GITHUB_SERVER_URL}/${env.GITHUB_REPOSITORY}/actions/runs/${env.GITHUB_RUN_ID}"},
-            { "title": "Pull Request", "value": "${env.GITHUB_SERVER_URL}/${env.GITHUB_REPOSITORY}/pull/${{ steps.pr.outputs.pull_request_number }}"}
-            ]
+  #     - name: Send slack notification
+  #       if: always()
+  #       uses: edge/simple-slack-notify@master
+  #       env:
+  #         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
+  #       with:
+  #         channel: '#wallet-bot'
+  #         status: ${{ job.status }}
+  #         success_text: 'iOS ${env.BUILD_NUMBER} completed successfully'
+  #         failure_text: 'iOS build failed'
+  #         cancelled_text: 'iOS build was cancelled'
+  #         fields: |
+  #           [{ "title": "Repository", "value": "${env.GITHUB_REPOSITORY}", "short": true },
+  #           { "title": "App version", "value": "${env.BUILD_NUMBER}", "short": true },
+  #           { "title": "Action URL", "value": "${env.GITHUB_SERVER_URL}/${env.GITHUB_REPOSITORY}/actions/runs/${env.GITHUB_RUN_ID}"},
+  #           { "title": "Pull Request", "value": "${env.GITHUB_SERVER_URL}/${env.GITHUB_REPOSITORY}/pull/${{ steps.pr.outputs.pull_request_number }}"}
+  #           ]
