fix: white label ci

diff --git a/.github/workflows/white-label.yml b/.github/workflows/white-label.yml
--- a/.github/workflows/white-label.yml
+++ b/.github/workflows/white-label.yml
@@ -129,97 +129,97 @@ jobs:
           cd ./android
           fastlane s3_upload
 
-  run-white-label-ios-builds:
-    runs-on: macos-latest
-    needs: setup_distribution_matrix
-    strategy:
-      fail-fast: false
-      matrix: ${{fromJson(needs.setup_distribution_matrix.outputs.matrix)}}
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v2
-        with:
-          token: "${{ secrets.GIT_ACCESS_TOKEN }}"
+  # run-white-label-ios-builds:
+  #   runs-on: macos-latest
+  #   needs: setup_distribution_matrix
+  #   strategy:
+  #     fail-fast: false
+  #     matrix: ${{fromJson(needs.setup_distribution_matrix.outputs.matrix)}}
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v2
+  #       with:
+  #         token: "${{ secrets.GIT_ACCESS_TOKEN }}"
 
-      - name: Get Pull Request Number
-        id: pr
-        run: echo "::set-output name=pull_request_number::$(gh pr view --json number -q .number || echo "")"
-        env:
-          GITHUB_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
+  #     - name: Get Pull Request Number
+  #       id: pr
+  #       run: echo "::set-output name=pull_request_number::$(gh pr view --json number -q .number || echo "")"
+  #       env:
+  #         GITHUB_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
 
-      - name: Setup node
-        uses: actions/setup-node@v3
-        with:
-          node-version: '16.x'
+  #     - name: Setup node
+  #       uses: actions/setup-node@v3
+  #       with:
+  #         node-version: '16.x'
 
-      - name: Copy in distribution configs
-        run: |
-          git clone "https://${{ secrets.ACCESS_TOKEN }}@github.com/docknetwork/${{ matrix.app }}.git" ../distro_configs
-          ls -R ../distro_configs
-          cp -r ../distro_configs/* .
-          grep -i "IOS_BUNDLE_ID" ../distro_configs/packaging.config >> $GITHUB_ENV
-          grep -i "MATCH_PASSWORD" ../distro_configs/packaging.config >> $GITHUB_ENV
-          echo "MATCH_REPOSITORY=https://${{ secrets.ACCESS_TOKEN }}@github.com/docknetwork/${{ matrix.app }}.git" >> $GITHUB_ENV
+  #     - name: Copy in distribution configs
+  #       run: |
+  #         git clone "https://${{ secrets.ACCESS_TOKEN }}@github.com/docknetwork/${{ matrix.app }}.git" ../distro_configs
+  #         ls -R ../distro_configs
+  #         cp -r ../distro_configs/* .
+  #         grep -i "IOS_BUNDLE_ID" ../distro_configs/packaging.config >> $GITHUB_ENV
+  #         grep -i "MATCH_PASSWORD" ../distro_configs/packaging.config >> $GITHUB_ENV
+  #         echo "MATCH_REPOSITORY=https://${{ secrets.ACCESS_TOKEN }}@github.com/docknetwork/${{ matrix.app }}.git" >> $GITHUB_ENV
 
-      - name: Run fastlane setup
-        env:
-          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
-          CERTS_REPO_URL: ${{ secrets.CERTS_REPO_URL }}
-          MATCH_REPO_URL: ${{ env.MATCH_REPOSITORY }}
-          MATCH_PASSWORD: ${{ env.MATCH_PASSWORD }}
-          FASTLANE_APP_IDENTIFIER: ${{ env.IOS_BUNDLE_ID }}
-          FASTLANE_PASSWORD: ${{ env.MATCH_PASSWORD }}
-          FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
-          FASTLANEAppStore__APPLE_APPLICATION_SPECIFIC_PASSWORD:  ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
-          FASTLANE_APPLE_ID: ${{ secrets.FASTLANE_APPLE_ID }}
-          FASTLANE_ITC_TEAM_ID: ${{ secrets.FASTLANE_ITC_TEAM_ID }}
-          FASTLANE_TEAM_ID: ${{ secrets.FASTLANE_TEAM_ID }}
-          ASC_KEY: ${{ secrets.ASC_KEY }}
-          ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
-          ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
-        run: |
-          echo "MATCH_REPO_URL is: ${{env.MATCH_REPO_URL}}"
-          echo "IOS_BUNDLE_ID is: ${{env.IOS_BUNDLE_ID}}"
-          echo "MATCH_REPO_URL is: ${{env.MATCH_REPOSITORY}}"
-          git config --global url."https://".insteadOf git://
-          xcodebuild -version
-          sed -i -e "s/labs.dock.DockApp/${{ env.IOS_BUNDLE_ID }}/g" ./ios/DockApp.xcodeproj/project.pbxproj
-          cat ./ios/DockApp.xcodeproj/project.pbxproj
-          rm ./ios/DockApp.xcodeproj/project.pbxproj-e
-          yarn install
-          git clone "https://${{ secrets.ACCESS_TOKEN }}@github.com/docknetwork/react-native-sdk.git" ../wallet-sdk
-          yarn --cwd ../wallet-sdk install
-          yarn sync-sdk
-          yarn build-sdk
-          echo "BUILD_NUMBER=$(node print-build-number)" >> $GITHUB_ENV
-          echo "BUILD_TAG=$(node print-build-number|tr -s ' ' '_')" >> $GITHUB_ENV
-          rm -rf ./certs
-          git clone "${{ secrets.CERTS_REPO_URL }}" ./certs
-          # Pull env variables from certs repo
-          # It will inject sentry token in the JS thread
-          cp -rf ./certs/.env ./
-          cd ./ios
-          pod install
-          fastlane build_no_upload
+  #     - name: Run fastlane setup
+  #       env:
+  #         ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
+  #         CERTS_REPO_URL: ${{ secrets.CERTS_REPO_URL }}
+  #         MATCH_REPO_URL: ${{ env.MATCH_REPOSITORY }}
+  #         MATCH_PASSWORD: ${{ env.MATCH_PASSWORD }}
+  #         FASTLANE_APP_IDENTIFIER: ${{ env.IOS_BUNDLE_ID }}
+  #         FASTLANE_PASSWORD: ${{ env.MATCH_PASSWORD }}
+  #         FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
+  #         FASTLANEAppStore__APPLE_APPLICATION_SPECIFIC_PASSWORD:  ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
+  #         FASTLANE_APPLE_ID: ${{ secrets.FASTLANE_APPLE_ID }}
+  #         FASTLANE_ITC_TEAM_ID: ${{ secrets.FASTLANE_ITC_TEAM_ID }}
+  #         FASTLANE_TEAM_ID: ${{ secrets.FASTLANE_TEAM_ID }}
+  #         ASC_KEY: ${{ secrets.ASC_KEY }}
+  #         ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
+  #         ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
+  #       run: |
+  #         echo "MATCH_REPO_URL is: ${{env.MATCH_REPO_URL}}"
+  #         echo "IOS_BUNDLE_ID is: ${{env.IOS_BUNDLE_ID}}"
+  #         echo "MATCH_REPO_URL is: ${{env.MATCH_REPOSITORY}}"
+  #         git config --global url."https://".insteadOf git://
+  #         xcodebuild -version
+  #         sed -i -e "s/labs.dock.DockApp/${{ env.IOS_BUNDLE_ID }}/g" ./ios/DockApp.xcodeproj/project.pbxproj
+  #         cat ./ios/DockApp.xcodeproj/project.pbxproj
+  #         rm ./ios/DockApp.xcodeproj/project.pbxproj-e
+  #         yarn install
+  #         git clone "https://${{ secrets.ACCESS_TOKEN }}@github.com/docknetwork/react-native-sdk.git" ../wallet-sdk
+  #         yarn --cwd ../wallet-sdk install
+  #         yarn sync-sdk
+  #         yarn build-sdk
+  #         echo "BUILD_NUMBER=$(node print-build-number)" >> $GITHUB_ENV
+  #         echo "BUILD_TAG=$(node print-build-number|tr -s ' ' '_')" >> $GITHUB_ENV
+  #         rm -rf ./certs
+  #         git clone "${{ secrets.CERTS_REPO_URL }}" ./certs
+  #         # Pull env variables from certs repo
+  #         # It will inject sentry token in the JS thread
+  #         cp -rf ./certs/.env ./
+  #         cd ./ios
+  #         pod install
+  #         fastlane build_no_upload
 
-      - name: Print build logs
-        if: always()
-        run: |
-          cat /Users/runner/Library/Logs/gym/DockApp-DockApp.log
+  #     - name: Print build logs
+  #       if: always()
+  #       run: |
+  #         cat /Users/runner/Library/Logs/gym/DockApp-DockApp.log
 
-      - name: Upload to S3
-        env:
-          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
-          S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
-          S3_APP_BUCKET: ${{ secrets.S3_APP_BUCKET }}
-          S3_REGION: ${{ secrets.S3_REGION }}
-          S3_ANDROID_IPA_DIR: ${{matrix.app}}
-          S3_ACL: ${{ secrets.S3_ACL }}
-          IPA_LOCATION: "./DockApp.ipa"
-        run: |
-          echo "${{env.BUILD_TAG}}"
-          cd ./ios
-          fastlane s3_upload
+  #     - name: Upload to S3
+  #       env:
+  #         S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
+  #         S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
+  #         S3_APP_BUCKET: ${{ secrets.S3_APP_BUCKET }}
+  #         S3_REGION: ${{ secrets.S3_REGION }}
+  #         S3_ANDROID_IPA_DIR: ${{matrix.app}}
+  #         S3_ACL: ${{ secrets.S3_ACL }}
+  #         IPA_LOCATION: "./DockApp.ipa"
+  #       run: |
+  #         echo "${{env.BUILD_TAG}}"
+  #         cd ./ios
+  #         fastlane s3_upload
 
   create-tag:
     runs-on: ubuntu-latest
